// Weapon definitions. Each player equips up to MAX_WEAPONS of these and switches with Q.
export const WEAPONS = {
  sword: {
    key: 'sword',
    label: 'Sword',
    type: 'melee',
    damage: 16,
    range: 60,
    arcDegrees: 80,
    cooldownMs: 380,
    knockback: 220,
    color: 0xdddddd,
  },
  bat: {
    key: 'bat',
    label: 'Bat',
    type: 'melee',
    damage: 22,
    range: 55,
    arcDegrees: 90,
    cooldownMs: 560,
    knockback: 340,
    color: 0xa0703a,
  },
  spear: {
    key: 'spear',
    label: 'Spear',
    type: 'melee',
    damage: 12,
    range: 90,
    arcDegrees: 40,
    cooldownMs: 340,
    knockback: 180,
    color: 0xd9a441,
  },
  pistol: {
    key: 'pistol',
    label: 'Pistol',
    type: 'ranged',
    damage: 10,
    cooldownMs: 340,
    projectileSpeed: 620,
    gravityScale: 0,
    knockback: 150,
    color: 0x555555,
  },
  bow: {
    key: 'bow',
    label: 'Bow',
    type: 'ranged',
    damage: 16,
    cooldownMs: 620,
    projectileSpeed: 480,
    gravityScale: 0.35,
    knockback: 160,
    color: 0x77aa44,
  },
  dagger: {
    key: 'dagger',
    label: 'Dagger',
    type: 'melee',
    damage: 8,
    range: 40,
    arcDegrees: 70,
    cooldownMs: 200,
    knockback: 100,
    color: 0x9fd8ff,
  },
  axe: {
    key: 'axe',
    label: 'Axe',
    type: 'melee',
    damage: 28,
    range: 65,
    arcDegrees: 70,
    cooldownMs: 700,
    knockback: 380,
    color: 0xc0392b,
  },
  shotgun: {
    key: 'shotgun',
    label: 'Shotgun',
    type: 'ranged',
    damage: 8,
    cooldownMs: 800,
    projectileSpeed: 560,
    gravityScale: 0,
    pellets: 5,
    spreadDegrees: 30,
    knockback: 90,
    color: 0xffb703,
  },
  crossbow: {
    key: 'crossbow',
    label: 'Crossbow',
    type: 'ranged',
    damage: 24,
    cooldownMs: 850,
    projectileSpeed: 720,
    gravityScale: 0.08,
    knockback: 190,
    color: 0x8d6e63,
  },
  rifle: {
    key: 'rifle',
    label: 'Rifle',
    type: 'ranged',
    damage: 13,
    cooldownMs: 200,
    projectileSpeed: 700,
    gravityScale: 0,
    knockback: 140,
    color: 0x3a3a3a,
  },
  smg: {
    key: 'smg',
    label: 'SMG',
    type: 'ranged',
    damage: 8,
    cooldownMs: 120,
    projectileSpeed: 640,
    gravityScale: 0,
    knockback: 90,
    color: 0x44464e,
  },
  sniper: {
    key: 'sniper',
    label: 'Sniper',
    type: 'ranged',
    damage: 36,
    cooldownMs: 1200,
    projectileSpeed: 900,
    gravityScale: 0,
    knockback: 260,
    color: 0x2b2b2b,
  },
  lmg: {
    key: 'lmg',
    label: 'LMG',
    type: 'ranged',
    damage: 11,
    cooldownMs: 150,
    projectileSpeed: 660,
    gravityScale: 0,
    knockback: 120,
    color: 0x3d4032,
  },
  katana: {
    key: 'katana',
    label: 'Katana',
    type: 'melee',
    damage: 20,
    range: 62,
    arcDegrees: 55,
    cooldownMs: 300,
    knockback: 200,
    color: 0xe8e8e8,
  },
  hammer: {
    key: 'hammer',
    label: 'Hammer',
    type: 'melee',
    damage: 32,
    range: 58,
    arcDegrees: 100,
    cooldownMs: 900,
    knockback: 480,
    color: 0x707070,
  },
  throwingKnife: {
    key: 'throwingKnife',
    label: 'Throwing Knife',
    type: 'ranged',
    damage: 9,
    cooldownMs: 160,
    projectileSpeed: 760,
    gravityScale: 0,
    knockback: 70,
    color: 0xb0b0b0,
  },
  rpg: {
    key: 'rpg',
    label: 'RPG',
    type: 'ranged',
    damage: 55,
    cooldownMs: 1400,
    projectileSpeed: 480,
    gravityScale: 0.05,
    knockback: 420,
    explosive: true,
    explosionRadius: 90,
    color: 0xd35400,
  },
  // Grenade family — same throw-and-explode mechanic, tuned along a
  // damage-vs-cooldown tradeoff: Frag is the balanced middle ground, Heavy
  // hits much harder but reloads much slower, Concussion reloads fast but
  // barely scratches HP (its value is the knockback, not the damage).
  grenade: {
    key: 'grenade',
    label: 'Frag Grenade',
    type: 'ranged',
    damage: 25,
    cooldownMs: 1000,
    projectileSpeed: 380,
    gravityScale: 0.55,
    knockback: 300,
    explosive: true,
    explosionRadius: 70,
    color: 0x4a5d23,
  },
  heavyGrenade: {
    key: 'heavyGrenade',
    label: 'Heavy Grenade',
    type: 'ranged',
    damage: 60,
    cooldownMs: 2000,
    projectileSpeed: 300,
    gravityScale: 0.6,
    knockback: 380,
    explosive: true,
    explosionRadius: 85,
    color: 0x6b1f1f,
  },
  stunGrenade: {
    key: 'stunGrenade',
    label: 'Concussion Grenade',
    type: 'ranged',
    damage: 10,
    cooldownMs: 500,
    projectileSpeed: 420,
    gravityScale: 0.5,
    knockback: 360,
    explosive: true,
    explosionRadius: 60,
    color: 0x8ec6e0,
  },
};

export const WEAPON_LIST = Object.values(WEAPONS);
export const MAX_WEAPONS = 3;

const MAX_DAMAGE = Math.max(...WEAPON_LIST.map((w) => w.damage));
const MAX_KNOCKBACK = Math.max(...WEAPON_LIST.filter((w) => w.type === 'melee').map((w) => w.knockback));
const MAX_PROJECTILE_SPEED = Math.max(...WEAPON_LIST.filter((w) => w.type === 'ranged').map((w) => w.projectileSpeed));
const MAX_MELEE_RANGE = Math.max(...WEAPON_LIST.filter((w) => w.type === 'melee').map((w) => w.range));
const CD_MIN = Math.min(...WEAPON_LIST.map((w) => w.cooldownMs));
const CD_MAX = Math.max(...WEAPON_LIST.map((w) => w.cooldownMs));

// Normalized 0-100 stat bars for the loadout UI, derived from the raw combat
// numbers above so a new weapon added to WEAPONS gets sane relative bars
// without hand-tuning.
export function getWeaponStats(weapon) {
  const rate = Math.round((1 - (weapon.cooldownMs - CD_MIN) / (CD_MAX - CD_MIN)) * 100);
  const power = weapon.type === 'melee'
    ? Math.round((weapon.knockback / MAX_KNOCKBACK) * 100)
    : Math.round((weapon.projectileSpeed / MAX_PROJECTILE_SPEED) * 100);
  const range = weapon.type === 'melee' ? Math.round((weapon.range / MAX_MELEE_RANGE) * 100) : 100;
  return {
    damage: Math.round((weapon.damage / MAX_DAMAGE) * 100),
    rate,
    power,
    range,
  };
}
